manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/nxtkb
    - name: jewtvet
      url-base: https://github.com/jewtvet
  projects:
    - name: zmk
      remote: zmk
      revision: main
      import: app/west.yml
    - name: zmk-ruen
      remote: jewtvet
      revision: main
  self:
    path: config
